---
title: "Lab 2 - Data wrangling"
author: "Quincy Vogelsang"
date: "February 8, 2026"
format: 
  html: default # for speed
  pdf: default # for final output
---

```{r}
#| eval: true
#| message: false

library(tidyverse)
```

# Questions

## Part 1

```{r}
?midwest

glimpse(midwest)
```

### Question 1

```{r}
midwest |>
  group_by(state) |>
  summarize(counties = n()) |>
  arrange(desc(counties))
  
```

The highest number of counties can be found in IL with 102 counties. The lowest number of counties can be found in WI with 72 counties.

\newpage

### Question 2

```{r}
midwest |>
  group_by(county) |>
  summarize(n_states = n()) |>
  filter(n_states == 5)
```

\newpage

### Question 3

```{r}

midwest |>
  filter(popdensity > 25000) |>
  arrange(desc(popdensity)) |>
  select(county, state, popdensity, poptotal, area)

```

```{r}

midwest |>
  filter(popdensity == max(popdensity)) |>
  select(county, state, popdensity, poptotal, area)
```

\newpage

### Question 5

\newpage

### Question 6

\newpage

### Question 7

\newpage

### Question 8

\newpage

## Part 2

### Question 9
